version: '3.8'

services:
  postgres:
    image: docker-proxy.artifactory.tcsbank.ru/postgres:latest
    container_name: crm_db
    restart: always
    environment:
      POSTGRES_DB: "crm_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: