export enum DealStatus {
    NEW = 'NEW',
    CONTACTED = 'CONTACTED',
    PROPOSAL_SENT = 'PROPOSAL_SENT',
    NEGOTIATION = 'NEGOTIATION',
    CLOSED_WON = 'CLOSED_WON',
    CLOSED_LOST = 'CLOSED_LOST',
    ON_HOLD = 'ON_HOLD',
    REJECTED = 'REJECTED',
    WAITING_FOR_PAYMENT = 'WAITING_FOR_PAYMENT',
    COMPLETED = 'COMPLETED',
}